version: '3.9'

services:
  prometheus:
    build: ./prometheus
    ports:
      - '9090:9090'
    links:
      - metrics
  metrics:
    build: ./metrics
    ports:
      - '8088:8088'
    links:
      - prometheus